package com.root.app.audio

import androidx.annotation.RawRes
import com.root.app.R

/**
 * Root's original interaction sounds (generated by `tools/audio/generate_root_sounds.py`).
 * One catalogue drives both playback and the Sound Lab. [pilot] marks cues that
 * may play automatically; the rest are audition-only until their placement is
 * reviewed. [durationMs] must match the shipped WAV (checked by a unit test):
 * SoundPool has no completion callback, so cleanup is timed from it.
 */
enum class RootSoundCue(
    @RawRes val resId: Int,
    val durationMs: Long,
    val label: String,
    val role: String,
    val pilot: Boolean,
) {
    ROOT_GROWTH(R.raw.root_sound_root_growth, 2_950, "Root growth",
        "The startup sound, timed to the opening: ink as the root draws, a tap for each branch, a settle for the wordmark.",
        pilot = true),
    BRAND_A(R.raw.root_sound_brand_a, 1_600, "Root motif A", "An earlier startup idea, kept for comparison.", pilot = false),
    BRAND_B(R.raw.root_sound_brand_b, 1_800, "Root motif B", "An earlier startup idea, kept for comparison.", pilot = false),
    REVEAL(R.raw.root_sound_reveal, 130, "Reveal", "When you reveal a word.", pilot = true),
    RECALL_ACKNOWLEDGED(R.raw.root_sound_recall_acknowledged, 400, "Got it", "After a Got it rating is saved.", pilot = true),
    ANSWER_CORRECT(R.raw.root_sound_answer_correct, 480, "Correct answer", "After a lesson answer is checked as correct.", pilot = true),
    LESSON_SETTLED(R.raw.root_sound_lesson_settled, 1_000, "Lesson finished", "When a lesson is completed.", pilot = true),
    NEUTRAL_SETTLE(R.raw.root_sound_neutral_settle, 260, "Neutral settle", "A gentle, non-judging tone. Not used yet.", pilot = false),
    SAVED(R.raw.root_sound_saved, 300, "Saved", "A candidate for saving a word. Not used yet.", pilot = false),
    PAGE_TOUCH(R.raw.root_sound_page_touch, 90, "Touch", "A candidate tactile accent. Not used yet.", pilot = false),
    ;

    /** The earlier, untimed jingle-style motifs, now Sound Lab-only. */
    val isMotif: Boolean get() = this == BRAND_A || this == BRAND_B

    companion object {
        /** The startup sound. It is scored to LaunchScreen's timing (RootMotion launch
         *  constants and the five RootGeometry branches) and starts with root growth;
         *  RootSoundCatalogueTest fails if the animation and this cue drift apart. */
        val STARTUP_MOTIF = ROOT_GROWTH
    }
}

/** How a sound was requested; decides which switches apply. */
enum class SoundRequest {
    /** A live pilot moment; needs the Sound effects switch. */
    AUTOMATIC,
    /** The launch motif; needs Sound effects and Startup sound. */
    STARTUP,
    /** An explicit Sound Lab tap; ignores both switches but no quiet rule. */
    PREVIEW,
}

/** Defaults: sound effects and the startup sound on, at full in-app volume
 *  (the cues themselves are mastered quiet, -8 to -24 dBFS). The quiet policy
 *  still applies, and the learner can turn either off in Profile → Sound. */
data class SoundSettings(
    val effectsEnabled: Boolean = DEFAULT_EFFECTS_ENABLED,
    val startupEnabled: Boolean = DEFAULT_STARTUP_ENABLED,
    val volume: Float = DEFAULT_VOLUME,
) {
    companion object {
        const val DEFAULT_EFFECTS_ENABLED = true
        const val DEFAULT_STARTUP_ENABLED = true
        const val DEFAULT_VOLUME = 1f
    }
}

/** Device and app state sampled immediately before playback. [known] is
 *  false when the platform state could not be read; policy then fails quiet. */
data class SoundConditions(
    val foreground: Boolean,
    val speechActive: Boolean,
    val known: Boolean = true,
    val inCall: Boolean = false,
    val ringerSilent: Boolean = false,
    val doNotDisturb: Boolean = false,
    val deviceVolumeZero: Boolean = false,
    val otherMediaActive: Boolean = false,
)

/** Why a request did not play. Suppression is expected, not an error. */
enum class SoundSuppression(val explanation: String) {
    DISABLED("Sound effects are off."),
    STARTUP_DISABLED("Startup sound is off."),
    MUTED_VOLUME("Sound effect volume is at zero."),
    BACKGROUND("Root isn't in the foreground."),
    SPEECH_ACTIVE("A recording or voice is playing."),
    STATE_UNKNOWN("Device sound state couldn't be read."),
    IN_CALL("A call is in progress."),
    RINGER_SILENT("The phone is on silent or vibrate."),
    DO_NOT_DISTURB("Do Not Disturb is on."),
    DEVICE_VOLUME_ZERO("System sound volume is at zero."),
    OTHER_MEDIA("Other audio is playing."),
    FOCUS_DENIED("Another app is using audio right now."),
    NOT_READY("Sounds are still loading. Try again in a moment."),
    ALREADY_PLAYING("Another sound is still playing."),
    COOLDOWN("Too soon after the last sound."),
}

sealed interface SoundResult {
    data object Played : SoundResult
    data class Suppressed(val reason: SoundSuppression) : SoundResult
    data class Failed(val message: String) : SoundResult
}

/** Pure decision: returns why [request] must stay silent, or null to play. */
object RootSoundPolicy {
    const val MIN_GAP_MS = 250L

    fun suppression(
        request: SoundRequest,
        settings: SoundSettings,
        conditions: SoundConditions,
        loaded: Boolean,
        busy: Boolean,
        sinceLastStartMs: Long?,
    ): SoundSuppression? {
        when (request) {
            SoundRequest.AUTOMATIC -> if (!settings.effectsEnabled) return SoundSuppression.DISABLED
            SoundRequest.STARTUP -> {
                if (!settings.effectsEnabled) return SoundSuppression.DISABLED
                if (!settings.startupEnabled) return SoundSuppression.STARTUP_DISABLED
            }
            SoundRequest.PREVIEW -> Unit
        }
        return when {
            settings.volume <= 0f -> SoundSuppression.MUTED_VOLUME
            !conditions.foreground -> SoundSuppression.BACKGROUND
            conditions.speechActive -> SoundSuppression.SPEECH_ACTIVE
            !conditions.known -> SoundSuppression.STATE_UNKNOWN
            conditions.inCall -> SoundSuppression.IN_CALL
            conditions.ringerSilent -> SoundSuppression.RINGER_SILENT
            conditions.doNotDisturb -> SoundSuppression.DO_NOT_DISTURB
            conditions.deviceVolumeZero -> SoundSuppression.DEVICE_VOLUME_ZERO
            conditions.otherMediaActive -> SoundSuppression.OTHER_MEDIA
            !loaded -> SoundSuppression.NOT_READY
            request == SoundRequest.PREVIEW -> null
            busy -> SoundSuppression.ALREADY_PLAYING
            sinceLastStartMs != null && sinceLastStartMs < MIN_GAP_MS -> SoundSuppression.COOLDOWN
            else -> null
        }
    }
}

/**
 * Remembers which one-time moments already produced a sound (for example a
 * practice queue entry or a lesson run's activity) so a replayed commit,
 * duplicate tap, or restored screen can never sound twice. Bounded.
 */
class SoundEventGate(private val capacity: Int = 64) {
    private val seen = LinkedHashSet<String>()

    fun firstTime(key: String): Boolean {
        if (!seen.add(key)) return false
        if (seen.size > capacity) seen.remove(seen.first())
        return true
    }
}

/** A short-lived request for an automatic cue, stamped with a monotonic time
 *  so a collector can drop one that arrives too late to match its moment. */
data class RootSoundEvent(val cue: RootSoundCue, val createdAtMs: Long) {
    fun isStale(nowMs: Long): Boolean = nowMs - createdAtMs > MAX_AGE_MS

    companion object {
        const val MAX_AGE_MS = 1_000L
    }
}
