package com.root.app.ui

import android.content.ActivityNotFoundException
import android.content.res.Resources
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.widthIn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.LiveRegionMode
import androidx.compose.ui.semantics.liveRegion
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.root.app.data.PhraseEntity
import com.root.app.data.ReferralPrefs
import com.root.app.sharing.PhraseCardException
import com.root.app.sharing.PhraseCardPalette
import com.root.app.sharing.PhraseCardSharing
import com.root.app.sharing.PreparedPhraseCard
import com.root.app.ui.icon.RootIcons
import com.root.app.ui.theme.RootTheme
import com.root.app.ui.theme.RootType
import java.io.IOException

private sealed interface ShareCardState {
    data object Loading : ShareCardState
    data object Empty : ShareCardState
    data class Ready(val card: PreparedPhraseCard) : ShareCardState
    data class Error(val message: String) : ShareCardState
}

/**
 * Renders a share-ready phrase card and its "teach someone one word" flow. State is
 * a private [ShareCardState] sealed type rather than loose booleans so Loading,
 * Empty (no due phrase yet), Ready, and Error stay mutually exclusive at compile time.
 * The card image itself is generated by [PhraseCardSharing.prepare]; this composable
 * only reacts to the result and triggers the system share sheet on [onShare].
 */
@Composable
fun InviteScreen(phrase: PhraseEntity?, languageName: String, onBack: () -> Unit) {
    val context = LocalContext.current
    val colors = MaterialTheme.colorScheme
    val palette = PhraseCardPalette(
        paper = colors.surface.toArgb(),
        ink = colors.onSurface.toArgb(),
        secondaryInk = colors.onSurfaceVariant.toArgb(),
        pigment = colors.tertiary.toArgb(),
        rule = colors.outlineVariant.toArgb(),
    )
    val rewardFlow = remember(context) { ReferralPrefs.observeReward(context) }
    val rewarded by rewardFlow.collectAsStateWithLifecycle(ReferralPrefs.hasUnlockedReward(context))
    var retry by remember { mutableIntStateOf(0) }
    var state by remember(phrase, languageName, palette) {
        mutableStateOf<ShareCardState>(if (phrase == null) ShareCardState.Empty else ShareCardState.Loading)
    }
    var shareError by remember(phrase) { mutableStateOf<String?>(null) }

    LaunchedEffect(phrase, languageName, palette, retry) {
        if (phrase == null) {
            state = ShareCardState.Empty
        } else {
            state = ShareCardState.Loading
            state = try {
                ShareCardState.Ready(PhraseCardSharing.prepare(context, phrase, languageName, palette))
            } catch (error: PhraseCardException) {
                ShareCardState.Error(error.message ?: "This phrase cannot be made into a card.")
            } catch (_: IOException) {
                ShareCardState.Error("The image could not be saved. Check the space on this device and try again.")
            } catch (_: Resources.NotFoundException) {
                ShareCardState.Error("The card fonts are missing from this build.")
            } catch (_: IllegalArgumentException) {
                ShareCardState.Error("Image sharing is not configured correctly in this build.")
            } catch (_: SecurityException) {
                ShareCardState.Error("This device did not allow the image to be prepared.")
            }
        }
    }

    InviteContent(
        phrase = phrase,
        languageName = languageName,
        state = state,
        rewarded = rewarded,
        shareError = shareError,
        onBack = onBack,
        onRetry = { retry++ },
        onShare = {
            val ready = state as? ShareCardState.Ready
            if (ready != null) {
                shareError = null
                try {
                    PhraseCardSharing.openShareSheet(context, ready.card)
                } catch (_: ActivityNotFoundException) {
                    shareError = "No sharing app is available on this device. The reward has not changed."
                } catch (_: SecurityException) {
                    shareError = "The device could not open this image for sharing. The reward has not changed."
                }
            } else {
                shareError = "Wait for your phrase card to finish, then try again."
            }
        },
    )
}

@Composable
private fun InviteContent(
    phrase: PhraseEntity?,
    languageName: String,
    state: ShareCardState,
    rewarded: Boolean,
    shareError: String?,
    onBack: () -> Unit,
    onRetry: () -> Unit = {},
    onShare: () -> Unit = {},
) {
    Scaffold { padding ->
        Box(Modifier.fillMaxSize().padding(padding), contentAlignment = Alignment.TopCenter) {
            Column(
                modifier = Modifier.widthIn(max = 640.dp).fillMaxSize()
                    .verticalScroll(rememberScrollState())
                    .padding(horizontal = 24.dp, vertical = 12.dp),
            ) {
                Row(
                    Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    IconButton(onClick = onBack) { Icon(RootIcons.Back, "Back") }
                    Text("PASS IT ON", style = MaterialTheme.typography.labelSmall)
                }
                Spacer(Modifier.height(28.dp))
                Text("Teach someone\none word.", style = RootType.editorialTitle)
                Spacer(Modifier.height(12.dp))
                Text(
                    "A small piece of $languageName, with room to travel.",
                    style = MaterialTheme.typography.bodyLarge,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                Spacer(Modifier.height(28.dp))
                Surface(
                    shape = RoundedCornerShape(6.dp),
                    border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant),
                    color = MaterialTheme.colorScheme.surface,
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    when (state) {
                        is ShareCardState.Ready -> Image(
                            bitmap = state.card.preview.asImageBitmap(),
                            contentDescription = "$languageName: ${phrase?.answer.orEmpty()}. ${phrase?.prompt.orEmpty()}. Root.",
                            modifier = Modifier.fillMaxWidth().aspectRatio(
                                state.card.preview.width.toFloat() / state.card.preview.height,
                            ),
                        )
                        ShareCardState.Loading -> Column(
                            Modifier.padding(40.dp),
                            verticalArrangement = Arrangement.spacedBy(20.dp),
                        ) {
                            CircularProgressIndicator(Modifier.size(24.dp), strokeWidth = 2.dp)
                            Text("Preparing your word card...", style = MaterialTheme.typography.bodyMedium)
                        }
                        ShareCardState.Empty -> Column(
                            Modifier.padding(28.dp),
                            verticalArrangement = Arrangement.spacedBy(12.dp),
                        ) {
                            Text("A word comes first.", style = RootType.editorialTitle)
                            Text(
                                "Practice a phrase, then come back to make a card from it.",
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                            )
                        }
                        is ShareCardState.Error -> Column(
                            Modifier.padding(24.dp),
                            verticalArrangement = Arrangement.spacedBy(16.dp),
                        ) {
                            Text(state.message, color = MaterialTheme.colorScheme.error)
                            OutlinedButton(onClick = onRetry, shape = RoundedCornerShape(4.dp)) { Text("Try again") }
                        }
                    }
                }
                Spacer(Modifier.height(24.dp))
                Button(
                    onClick = onShare,
                    enabled = state is ShareCardState.Ready,
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(4.dp),
                    contentPadding = androidx.compose.foundation.layout.PaddingValues(16.dp),
                ) {
                    Icon(RootIcons.Share, null, Modifier.size(20.dp))
                    Text("Share word card", Modifier.padding(start = 12.dp))
                }
                Spacer(Modifier.height(20.dp))
                Column(
                    Modifier.semantics { liveRegion = LiveRegionMode.Polite },
                    verticalArrangement = Arrangement.spacedBy(8.dp),
                ) {
                    shareError?.let { Text(it, color = MaterialTheme.colorScheme.error) }
                    Text(
                        if (rewarded) "Your Market pack is unlocked."
                        else "Open the share sheet. Unlock Market.",
                        style = MaterialTheme.typography.titleMedium,
                    )
                    Text(
                        "Opening the share sheet unlocks the Dholuo Market pack on this device, " +
                            "even if you cancel without sending. We cannot verify delivery or a friend's install.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                    Text(
                        "Your card includes only this phrase, its meaning and language. No invite code or tracking link.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                Spacer(Modifier.height(28.dp))
            }
        }
    }
}

@Preview(name = "Share / paper / no phrase", showBackground = true)
@Preview(name = "Share / charcoal / no phrase", showBackground = true, uiMode = android.content.res.Configuration.UI_MODE_NIGHT_YES)
@Composable
private fun InvitePreview() {
    RootTheme {
        InviteContent(
            phrase = null,
            languageName = "Dholuo",
            state = ShareCardState.Empty,
            rewarded = false,
            shareError = null,
            onBack = {},
        )
    }
}
